import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App + wagmi",
  description: "Generated by create next app",
};

export default function DefaultLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <main className="flex-1 bg-[url('/images/background.png')] relative bg-[#1B1F24]">
        {/* <div className="absolute bg-[#000000] w-full h-full opacity-40">
        </div> */}
          {children}
      </main>
      <Footer />
    </>
  );
}
